### ISSUE TITLE
RichEmbed field values may not be empty.

### ISSUE THREAD

**Issue by benrobson** [shadowolfyt/Rodney#84]
Error:

C:\Users\Anastasia\Documents\GitHub\RodneyTheDiscordBot\node_modules\discord.js\s
rc\structures\RichEmbed.js:158
    if (!/\S/.test(value)) throw new RangeError('RichEmbed field values may not b
e empty.');
                           ^

RangeError: RichEmbed field values may not be empty.
    at RichEmbed.addField (C:\Users\Anastasia\Documents\GitHub\RodneyTheDiscordBo
t\node_modules\discord.js\src\structures\RichEmbed.js:158:34)
    at Client.module.exports (C:\Users\Anastasia\Documents\GitHub\RodneyTheDiscor
dBot\events\messageDelete.js:17:4)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at MessageDeleteHandler.handle (C:\Users\Anastasia\Documents\GitHub\RodneyThe
DiscordBot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageD
elete.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Anastasia\Documents\GitHub\RodneyT
heDiscordBot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacket
Manager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Anastasia\Documents\GitHub\RodneyTh
eDiscordBot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:3
33:35)
    at WebSocketConnection.onMessage (C:\Users\Anastasia\Documents\GitHub\RodneyT
heDiscordBot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:
296:17)
    at WebSocket.onMessage (C:\Users\Anastasia\Documents\GitHub\RodneyTheDiscordB
ot\node_modules\ws\lib\event-target.js:120:16)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (C:\Users\Anastasia\Documents\GitHub\RodneyTh
eDiscordBot\node_modules\ws\lib\websocket.js:137:47)
    at Receiver.dataMessage (C:\Users\Anastasia\Documents\GitHub\RodneyTheDiscord
Bot\node_modules\ws\lib\receiver.js:409:14)
    at Receiver.getData (C:\Users\Anastasia\Documents\GitHub\RodneyTheDiscordBot\
node_modules\ws\lib\receiver.js:347:12)
    at Receiver.startLoop (C:\Users\Anastasia\Documents\GitHub\RodneyTheDiscordBo
t\node_modules\ws\lib\receiver.js:143:16)
    at Receiver.add (C:\Users\Anastasia\Documents\GitHub\RodneyTheDiscordBot\node
_modules\ws\lib\receiver.js:117:10)

**Comment by Taha-Chaudhry** [comment]
Could you tell me what you did to fix this problem? i am still incapable of fixing it.

**Comment by benrobson** [comment]
@Taha-Chaudhry this isn't the place for support. Visit the [Discord](http://bit.ly/mancavediscord) for assistance.
