### ISSUE TITLE
Error in fortnite command needs fixing.

### ISSUE THREAD

**Issue by benrobson** [shadowolfyt/Rodney#99]
2018-09-03T01:52:07.190537+00:00 app[worker.1]: /app/commands/fortnite.js:6
2018-09-03T01:52:07.190539+00:00 app[worker.1]: const stats = new Client(fortniteapi);
2018-09-03T01:52:07.190540+00:00 app[worker.1]:               ^
2018-09-03T01:52:07.190542+00:00 app[worker.1]: 
2018-09-03T01:52:07.190543+00:00 app[worker.1]: TypeError: Client is not a constructor
2018-09-03T01:52:07.190544+00:00 app[worker.1]:     at Object.<anonymous> (/app/commands/fortnite.js:6:15)
2018-09-03T01:52:07.190545+00:00 app[worker.1]:     at Module._compile (module.js:652:30)
2018-09-03T01:52:07.190546+00:00 app[worker.1]:     at Object.Module._extensions..js (module.js:663:10)
2018-09-03T01:52:07.190547+00:00 app[worker.1]:     at Module.load (module.js:565:32)
2018-09-03T01:52:07.190548+00:00 app[worker.1]:     at tryModuleLoad (module.js:505:12)
2018-09-03T01:52:07.190550+00:00 app[worker.1]:     at Function.Module._load (module.js:497:3)
2018-09-03T01:52:07.190551+00:00 app[worker.1]:     at Module.require (module.js:596:17)
2018-09-03T01:52:07.190552+00:00 app[worker.1]:     at require (internal/module.js:11:18)
2018-09-03T01:52:07.190553+00:00 app[worker.1]:     at jsfile.forEach (/app/index.js:18:17)
2018-09-03T01:52:07.190554+00:00 app[worker.1]:     at Array.forEach (<anonymous>)

**Comment by benrobson** [comment]
Hey @abhinavk99 I think you could help out with this one if you can :)

**Comment by abhinavk99** [comment]
I'm not really sure, I think it might be a problem with the fortnite npm library. I recommend using https://github.com/ickerio/fortnite.js (which I helped work on lol).
